import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("desktop installer is user-scoped and registers launch integration", async () => {
  const install = await readFile(new URL("../installer/install-helper.ps1", import.meta.url), "utf8");
  const uninstall = await readFile(new URL("../installer/uninstall-helper.ps1", import.meta.url), "utf8");
  const builder = await readFile(new URL("../scripts/build-helper-exe.mjs", import.meta.url), "utf8");
  const installerBuilder = await readFile(new URL("../scripts/build-helper-installer.mjs", import.meta.url), "utf8");
  const installCommand = await readFile(new URL("../installer/install.cmd", import.meta.url), "utf8");
  const client = await readFile(new URL("../lib/local-client.ts", import.meta.url), "utf8");
  const dashboard = await readFile(new URL("../app/HaiDouDashboard.tsx", import.meta.url), "utf8");

  assert.match(install, /FolderBrowserDialog/);
  assert.match(install, /InstallLocation/);
  assert.match(install, /\.haidou-helper-install/);
  assert.doesNotMatch(install, /\$installDirectory\s*=\s*Join-Path\s+\$env:LOCALAPPDATA/);
  assert.match(install, /legacyInstallDirectory/);
  assert.match(install, /HKCU:\\Software\\Classes\\haidou-helper/);
  assert.match(install, /CurrentVersion\\Run/);
  assert.match(install, /CurrentVersion\\Uninstall\\HaiDouHelper/);
  assert.match(install, /requiredInstalledFiles/);
  assert.match(install, /start-hidden\.vbs/);
  assert.match(install, /missingInstalledFiles\.Count -gt 0/);
  assert.match(install, /Get-RunningHaiDouHelper/);
  assert.match(install, /Wait-Process -Id \$process\.Id -Timeout 8/);
  assert.match(install, /旧版助手仍在运行，更新已安全停止/);
  assert.match(install, /installedHealth\.version -ge \$expectedHelperApiVersion/);
  assert.match(install, /HaiDouHelper-install\.log/);
  assert.doesNotMatch(install, /HKLM:/);
  assert.match(uninstall, /Software\\Classes\\haidou-helper/);
  assert.match(uninstall, /InstallLocation/);
  assert.match(uninstall, /\.haidou-helper-install/);
  assert.doesNotMatch(uninstall, /rmdir \/s \/q/i);
  assert.doesNotMatch(installCommand, /ExecutionPolicy\s+Bypass/i);
  assert.match(builder, /experimental-sea-config/);
  assert.match(builder, /NODE_SEA_BLOB/);
  assert.match(builder, /stripEmbeddedSignature/);
  assert.match(installerBuilder, /signWindowsArtifact/);
  assert.match(client, /releases\/latest\/download\/HaiDouHelperSetup\.exe/);
  assert.match(client, /haidou-helper:\/\/start/);
  assert.match(client, /MIN_HELPER_VERSION = 17/);
  assert.match(dashboard, /\{!needsUpdate && \(/);
  assert.match(dashboard, /更新助手（自动关闭旧版）/);
  assert.match(dashboard, /安装器会关闭旧助手、完成覆盖并自动重启/);
});
