import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("desktop installer is user-scoped and registers launch integration", async () => {
  const install = await readFile(new URL("../installer/HaiDouInstaller.cs", import.meta.url), "utf8");
  const builder = await readFile(new URL("../scripts/build-helper-exe.mjs", import.meta.url), "utf8");
  const installerBuilder = await readFile(new URL("../scripts/build-helper-installer.mjs", import.meta.url), "utf8");
  const client = await readFile(new URL("../lib/local-client.ts", import.meta.url), "utf8");
  const dashboard = await readFile(new URL("../app/HaiDouDashboard.tsx", import.meta.url), "utf8");

  assert.match(install, /FolderBrowserDialog/);
  assert.match(install, /InstallLocation/);
  assert.match(install, /\.haidou-helper-install/);
  assert.match(install, /Registry\.CurrentUser/);
  assert.match(install, /Software\\Classes\\haidou-helper/);
  assert.match(install, /CurrentVersion\\Run/);
  assert.match(install, /CurrentVersion\\Uninstall\\HaiDouHelper/);
  assert.match(install, /start-hidden\.vbs/);
  assert.match(install, /WaitForExit\(8000\)/);
  assert.match(install, /旧版助手仍在运行，更新已安全停止/);
  assert.match(install, /HaiDouHelper-install\.log/);
  assert.match(install, /new ProgressBar/);
  assert.match(install, /检测当前版本/);
  assert.match(install, /关闭旧版助手/);
  assert.match(install, /复制并校验文件/);
  assert.match(install, /确认接口达到 V17/);
  assert.match(install, /安装成功：海斗数据助手 V17 已启动/);
  assert.match(install, /\/preview/);
  assert.match(install, /\/uninstall/);
  assert.match(install, /HaiDouHelperInstaller\.exe/);
  assert.match(install, /health\.Version >= Program\.ApiVersion/);
  assert.doesNotMatch(install, /HKLM:/);
  assert.doesNotMatch(install, /powershell/i);
  assert.match(builder, /experimental-sea-config/);
  assert.match(builder, /NODE_SEA_BLOB/);
  assert.match(builder, /stripEmbeddedSignature/);
  assert.match(installerBuilder, /signWindowsArtifact/);
  assert.match(installerBuilder, /csc\.exe/);
  assert.match(installerBuilder, /target:winexe/);
  assert.match(installerBuilder, /ShowInstallProgramWindow=0/);
  assert.match(installerBuilder, /InstallPrompt=\\r\\nDisplayLicense=/);
  assert.match(installerBuilder, /AppLaunched=HaiDouInstaller\.exe/);
  assert.doesNotMatch(installerBuilder, /Install HaiDou Data Helper for the current Windows user/);
  assert.doesNotMatch(installerBuilder, /install-helper\.ps1|install\.cmd/);
  assert.match(client, /releases\/latest\/download\/HaiDouHelperSetup\.exe/);
  assert.match(client, /haidou-helper:\/\/start/);
  assert.match(client, /MIN_HELPER_VERSION = 17/);
  assert.match(dashboard, /\{!needsUpdate && \(/);
  assert.match(dashboard, /更新助手（自动关闭旧版）/);
  assert.match(dashboard, /安装器会关闭旧助手、完成覆盖并自动重启/);
});
